#ifndef NODE_BUILD_CONFIG_H
#define NODE_BUILD_CONFIG_H

#include "node_profile.h"

//#define ACTIVE_NODE_PROFILE NODE_PROFILE_DUMMY
//#define ACTIVE_NODE_PROFILE NODE_PROFILE_MOTOR_BASIC
//#define ACTIVE_NODE_PROFILE NODE_PROFILE_SENSOR_BASIC
#define ACTIVE_NODE_PROFILE NODE_PROFILE_SERVO_BASIC


#endif